CREATE TABLE `training_raw` (
  `RefID` int(11) NOT NULL,
  `IsBadBuy` int(11) DEFAULT NULL,
  `PurchDate` date DEFAULT NULL,
  `Auction` varchar(90) DEFAULT NULL,
  `VehYear` int(11) DEFAULT NULL,
  `VehicleAge` int(11) DEFAULT NULL,
  `Make` varchar(90) DEFAULT NULL,
  `Model` varchar(255) DEFAULT NULL,
  `Trim` varchar(45) DEFAULT NULL,
  `SubModel` varchar(255) DEFAULT NULL,
  `Color` varchar(45) DEFAULT NULL,
  `Transmission` varchar(45) DEFAULT NULL,
  `WheelTypeID` int(11) DEFAULT NULL,
  `WheelType` varchar(45) DEFAULT NULL,
  `VehOdo` int(11) DEFAULT NULL,
  `Nationality` varchar(255) DEFAULT NULL,
  `Size` varchar(80) DEFAULT NULL,
  `TopThreeAmericanName` varchar(255) DEFAULT NULL,
  `MMRAcquisitionAuctionAveragePrice` decimal(10,0) DEFAULT NULL,
  `MMRAcquisitionAuctionCleanPrice` decimal(10,0) DEFAULT NULL,
  `MMRAcquisitionRetailAveragePrice` decimal(10,0) DEFAULT NULL,
  `MMRAcquisitonRetailCleanPrice` decimal(10,0) DEFAULT NULL,
  `MMRCurrentAuctionAveragePrice` decimal(10,0) DEFAULT NULL,
  `MMRCurrentAuctionCleanPrice` decimal(10,0) DEFAULT NULL,
  `MMRCurrentRetailAveragePrice` decimal(10,0) DEFAULT NULL,
  `MMRCurrentRetailCleanPrice` decimal(10,0) DEFAULT NULL,
  `PRIMEUNIT` varchar(45) DEFAULT NULL,
  `AUCGUART` varchar(45) DEFAULT NULL,
  `BYRNO` int(11) DEFAULT NULL,
  `VNZIP1` int(11) DEFAULT NULL,
  `VNST` varchar(45) DEFAULT NULL,
  `VehBCost` decimal(10,0) DEFAULT NULL,
  `IsOnlineSale` int(11) DEFAULT NULL,
  `WarrantyCost` decimal(10,0) DEFAULT NULL,
  PRIMARY KEY (`RefID`),
  KEY `IsBadBuy` (`IsBadBuy`),
  KEY `Size` (`Size`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `test_raw` (
  `RefID` int(11) NOT NULL,
  `PurchDate` date DEFAULT NULL,
  `Auction` varchar(90) DEFAULT NULL,
  `VehYear` int(11) DEFAULT NULL,
  `VehicleAge` int(11) DEFAULT NULL,
  `Make` varchar(90) DEFAULT NULL,
  `Model` varchar(255) DEFAULT NULL,
  `Trim` varchar(45) DEFAULT NULL,
  `SubModel` varchar(255) DEFAULT NULL,
  `Color` varchar(45) DEFAULT NULL,
  `Transmission` varchar(45) DEFAULT NULL,
  `WheelTypeID` int(11) DEFAULT NULL,
  `WheelType` varchar(45) DEFAULT NULL,
  `VehOdo` int(11) DEFAULT NULL,
  `Nationality` varchar(255) DEFAULT NULL,
  `Size` varchar(80) DEFAULT NULL,
  `TopThreeAmericanName` varchar(255) DEFAULT NULL,
  `MMRAcquisitionAuctionAveragePrice` decimal(10,0) DEFAULT NULL,
  `MMRAcquisitionAuctionCleanPrice` decimal(10,0) DEFAULT NULL,
  `MMRAcquisitionRetailAveragePrice` decimal(10,0) DEFAULT NULL,
  `MMRAcquisitonRetailCleanPrice` decimal(10,0) DEFAULT NULL,
  `MMRCurrentAuctionAveragePrice` decimal(10,0) DEFAULT NULL,
  `MMRCurrentAuctionCleanPrice` decimal(10,0) DEFAULT NULL,
  `MMRCurrentRetailAveragePrice` decimal(10,0) DEFAULT NULL,
  `MMRCurrentRetailCleanPrice` decimal(10,0) DEFAULT NULL,
  `PRIMEUNIT` varchar(45) DEFAULT NULL,
  `AUCGUART` varchar(45) DEFAULT NULL,
  `BYRNO` int(11) DEFAULT NULL,
  `VNZIP1` int(11) DEFAULT NULL,
  `VNST` varchar(45) DEFAULT NULL,
  `VehBCost` decimal(10,0) DEFAULT NULL,
  `IsOnlineSale` int(11) DEFAULT NULL,
  `WarrantyCost` decimal(10,0) DEFAULT NULL,
  PRIMARY KEY (`RefID`),
  KEY `Size` (`Size`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `training_raw_with_MM_YYYY` (
  `RefID` int(11) NOT NULL,
  `IsBadBuy` int(11) DEFAULT NULL,
  `PurchDate` date DEFAULT NULL,
  `PurchMonth` varchar(90) DEFAULT NULL,
  `PurchYear` int(11) DEFAULT NULL,
  `Auction` varchar(90) DEFAULT NULL,
  `VehYear` int(11) DEFAULT NULL,
  `VehicleAge` int(11) DEFAULT NULL,
  `Make` varchar(90) DEFAULT NULL,
  `Model` varchar(255) DEFAULT NULL,
  `Trim` varchar(45) DEFAULT NULL,
  `SubModel` varchar(255) DEFAULT NULL,
  `Color` varchar(45) DEFAULT NULL,
  `Transmission` varchar(45) DEFAULT NULL,
  `WheelTypeID` int(11) DEFAULT NULL,
  `WheelType` varchar(45) DEFAULT NULL,
  `VehOdo` int(11) DEFAULT NULL,
  `Nationality` varchar(255) DEFAULT NULL,
  `Size` varchar(80) DEFAULT NULL,
  `TopThreeAmericanName` varchar(255) DEFAULT NULL,
  `MMRAcquisitionAuctionAveragePrice` decimal(10,0) DEFAULT NULL,
  `MMRAcquisitionAuctionCleanPrice` decimal(10,0) DEFAULT NULL,
  `MMRAcquisitionRetailAveragePrice` decimal(10,0) DEFAULT NULL,
  `MMRAcquisitonRetailCleanPrice` decimal(10,0) DEFAULT NULL,
  `MMRCurrentAuctionAveragePrice` decimal(10,0) DEFAULT NULL,
  `MMRCurrentAuctionCleanPrice` decimal(10,0) DEFAULT NULL,
  `MMRCurrentRetailAveragePrice` decimal(10,0) DEFAULT NULL,
  `MMRCurrentRetailCleanPrice` decimal(10,0) DEFAULT NULL,
  `PRIMEUNIT` varchar(45) DEFAULT NULL,
  `AUCGUART` varchar(45) DEFAULT NULL,
  `BYRNO` int(11) DEFAULT NULL,
  `VNZIP1` int(11) DEFAULT NULL,
  `VNST` varchar(45) DEFAULT NULL,
  `VehBCost` decimal(10,0) DEFAULT NULL,
  `IsOnlineSale` int(11) DEFAULT NULL,
  `WarrantyCost` decimal(10,0) DEFAULT NULL,
  PRIMARY KEY (`RefID`),
  KEY `IsBadBuy` (`IsBadBuy`),
  KEY `Size` (`Size`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `test_raw_with_MM_YYYY` (
  `RefID` int(11) NOT NULL,
  `PurchDate` date DEFAULT NULL,
  `PurchMonth` varchar(90) DEFAULT NULL,
  `PurchYear` int(11) DEFAULT NULL,
  `Auction` varchar(90) DEFAULT NULL,
  `VehYear` int(11) DEFAULT NULL,
  `VehicleAge` int(11) DEFAULT NULL,
  `Make` varchar(90) DEFAULT NULL,
  `Model` varchar(255) DEFAULT NULL,
  `Trim` varchar(45) DEFAULT NULL,
  `SubModel` varchar(255) DEFAULT NULL,
  `Color` varchar(45) DEFAULT NULL,
  `Transmission` varchar(45) DEFAULT NULL,
  `WheelTypeID` int(11) DEFAULT NULL,
  `WheelType` varchar(45) DEFAULT NULL,
  `VehOdo` int(11) DEFAULT NULL,
  `Nationality` varchar(255) DEFAULT NULL,
  `Size` varchar(80) DEFAULT NULL,
  `TopThreeAmericanName` varchar(255) DEFAULT NULL,
  `MMRAcquisitionAuctionAveragePrice` decimal(10,0) DEFAULT NULL,
  `MMRAcquisitionAuctionCleanPrice` decimal(10,0) DEFAULT NULL,
  `MMRAcquisitionRetailAveragePrice` decimal(10,0) DEFAULT NULL,
  `MMRAcquisitonRetailCleanPrice` decimal(10,0) DEFAULT NULL,
  `MMRCurrentAuctionAveragePrice` decimal(10,0) DEFAULT NULL,
  `MMRCurrentAuctionCleanPrice` decimal(10,0) DEFAULT NULL,
  `MMRCurrentRetailAveragePrice` decimal(10,0) DEFAULT NULL,
  `MMRCurrentRetailCleanPrice` decimal(10,0) DEFAULT NULL,
  `PRIMEUNIT` varchar(45) DEFAULT NULL,
  `AUCGUART` varchar(45) DEFAULT NULL,
  `BYRNO` int(11) DEFAULT NULL,
  `VNZIP1` int(11) DEFAULT NULL,
  `VNST` varchar(45) DEFAULT NULL,
  `VehBCost` decimal(10,0) DEFAULT NULL,
  `IsOnlineSale` int(11) DEFAULT NULL,
  `WarrantyCost` decimal(10,0) DEFAULT NULL,
  PRIMARY KEY (`RefID`),
  KEY `Size` (`Size`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `training_exluding_f5_f8_f9_f10_f11_f13_f27_f28_f30` (
  `RefID` int(11) NOT NULL,
  `PurchDate` date DEFAULT NULL,
  `PurchMonth` varchar(90) DEFAULT NULL,
  `PurchYear` int(11) DEFAULT NULL,
  `Auction` varchar(90) DEFAULT NULL,
  `VehicleAge` varchar(90) DEFAULT NULL,
  `Make` varchar(90) DEFAULT NULL,
  `Transmission` varchar(45) DEFAULT NULL,
  `WheelType` varchar(45) DEFAULT NULL,
  `VehOdo` varchar(90) DEFAULT NULL,
  `Nationality` varchar(255) DEFAULT NULL,
  `Size` varchar(80) DEFAULT NULL,
  `TopThreeAmericanName` varchar(255) DEFAULT NULL,
  `MMRAcquisitionAuctionAveragePrice` varchar(90) DEFAULT NULL,
  `MMRAcquisitionAuctionCleanPrice` varchar(90) DEFAULT NULL,
  `MMRAcquisitionRetailAveragePrice` varchar(90) DEFAULT NULL,
  `MMRAcquisitonRetailCleanPrice` varchar(90) DEFAULT NULL,
  `MMRCurrentAuctionAveragePrice` varchar(90) DEFAULT NULL,
  `MMRCurrentAuctionCleanPrice` varchar(90) DEFAULT NULL,
  `MMRCurrentRetailAveragePrice` varchar(90) DEFAULT NULL,
  `MMRCurrentRetailCleanPrice` varchar(90) DEFAULT NULL,
  `BYRNO` varchar(90) DEFAULT NULL,
  `VNST` varchar(45) DEFAULT NULL,
  `VehBCost` varchar(90) DEFAULT NULL,
  `IsOnlineSale` int(11) DEFAULT NULL,
  `WarrantyCost` varchar(90) DEFAULT NULL,
  `IsBadBuy` int(11) DEFAULT NULL,
  PRIMARY KEY (`RefID`),
  KEY `IsBadBuy` (`IsBadBuy`),
  KEY `Size` (`Size`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `test_exluding_f5_f8_f9_f10_f11_f13_f27_f28_f30` (
  `RefID` int(11) NOT NULL,
  `PurchDate` date DEFAULT NULL,
  `PurchMonth` varchar(90) DEFAULT NULL,
  `PurchYear` int(11) DEFAULT NULL,
  `Auction` varchar(90) DEFAULT NULL,
  `VehicleAge` varchar(90) DEFAULT NULL,
  `Make` varchar(90) DEFAULT NULL,
  `Transmission` varchar(45) DEFAULT NULL,
  `WheelType` varchar(45) DEFAULT NULL,
  `VehOdo` varchar(90) DEFAULT NULL,
  `Nationality` varchar(255) DEFAULT NULL,
  `Size` varchar(80) DEFAULT NULL,
  `TopThreeAmericanName` varchar(255) DEFAULT NULL,
  `MMRAcquisitionAuctionAveragePrice` varchar(90) DEFAULT NULL,
  `MMRAcquisitionAuctionCleanPrice` varchar(90) DEFAULT NULL,
  `MMRAcquisitionRetailAveragePrice` varchar(90) DEFAULT NULL,
  `MMRAcquisitonRetailCleanPrice` varchar(90) DEFAULT NULL,
  `MMRCurrentAuctionAveragePrice` varchar(90) DEFAULT NULL,
  `MMRCurrentAuctionCleanPrice` varchar(90) DEFAULT NULL,
  `MMRCurrentRetailAveragePrice` varchar(90) DEFAULT NULL,
  `MMRCurrentRetailCleanPrice` varchar(90) DEFAULT NULL,
  `BYRNO` varchar(90) DEFAULT NULL,
  `VNST` varchar(45) DEFAULT NULL,
  `VehBCost` varchar(90) DEFAULT NULL,
  `IsOnlineSale` int(11) DEFAULT NULL,
  `WarrantyCost` varchar(90) DEFAULT NULL,
  PRIMARY KEY (`RefID`),
  KEY `Size` (`Size`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE training_exluding_f5_f8_f9_f10_f11_f13_f27_f28_f30_discretized AS 
  SELECT *
  FROM training_exluding_f5_f8_f9_f10_f11_f13_f27_f28_f30;
  
CREATE TABLE test_exluding_f5_f8_f9_f10_f11_f13_f27_f28_f30_discretized AS 
  SELECT *
  FROM test_exluding_f5_f8_f9_f10_f11_f13_f27_f28_f30;
